project_id = "qhzefqdrucocwzmadbvr"

[functions.process-bulk-import]
verify_jwt = true

[functions.get-gmb-reviews]
verify_jwt = false

[functions.send-review-request]
verify_jwt = false

[functions.process-review-emails]
verify_jwt = false
